### ISSUE TITLE
Usage of \mkbibemph instead of \mkbibitalics

### ISSUE THREAD

**Issue by dachem** [josephwright/biblatex-chem#11]
At least within chem-angew, \mkbibemph is used to get italic journal or book titles, and \mkbibemph defaults to \emph{}.

If you change \emph{} in your document, this breaks the complete citation style.

I tried to mitigate this by using \let\mkbibemph\mkbibitalic (which both now cleanly expand to \textit), but this does not solve the issue. I have the feeling, this is a problem of biblatex, but nevertheless \mkbibemph should not be used to get reliably italic formated text.

[Edit: \mkbibitalic of course. Without "-s" in the end :-)]

**Comment by josephwright** [comment]
I see your point, but also it's tricky to say if bibliography styles use 'italic' or 'emphasis' (we have no design spec!). I'll adjust.

**Comment by dachem** [comment]
Thanks for pointing out that the style could indeed use emphasis instead of italics, I did not consider that. There are definitly too few examles to decide if it's 'emphasis' or 'italic', so I think it's best to try to reproduce the (italic) appearance reliably.

Thanks for your effort!
