### ISSUE TITLE
Spurious comma when used with beamer

### ISSUE THREAD

**Issue by u-fischer** [josephwright/biblatex-chem#12]
When I compile this document

```
\documentclass{beamer}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{csquotes}
\usepackage[backend=biber, style=chem-angew]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\begin{frame}
\cite{doody}
\printbibliography
\end{frame}
```

I see an additional comma:

![bib-chem](https://cloud.githubusercontent.com/assets/4047173/15503269/47ec1b8e-21b9-11e6-904e-0b6e2f1e52dd.PNG)

With the article class (and without the frame) the output is fine.

**Comment by josephwright** [comment]
My guess is this is an issue a the `beamer` end, likely related to https://github.com/josephwright/beamer/issues/331. I'll open an issue there and close there.
