### ISSUE TITLE
Prints DOI despite doi=false is set

### ISSUE THREAD

**Issue by derbildschrim** [josephwright/biblatex-chem#15]
Hello,

one citation in my bibliography is printed with its doi despite setting doi=false.
I've included a minimal example with one citation that works correct and the false one.
I can't find the mistake.

Thank you for your help. 

[document.tex.txt](https://github.com/josephwright/biblatex-chem/files/3289969/document.tex.txt)
[bib.bib.txt](https://github.com/josephwright/biblatex-chem/files/3289970/bib.bib.txt)
[document.pdf](https://github.com/josephwright/biblatex-chem/files/3289937/document.pdf)

**Comment by josephwright** [comment]
Your database entry has no page numbers, therefore the DOI is *required* to be printed to identify the article. This is not affected by the `doi` setting.

**Comment by derbildschrim** [comment]
I did not know that. Works as inteded then. Fixed it. 
Thank you for your quick answer.
