### ISSUE TITLE
Double puntcuation when title is shown

### ISSUE THREAD

**Issue by moewew** [josephwright/biblatex-chem#16]
Via https://tex.stackexchange.com/q/505296/35864

## `chem-biochem` & `chem-acs`

Consider
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=chem-acs, backend=biber]{biblatex}


\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{geer}
\printbibliography
\end{document}
```

> Geer, I. de Earl, Saint, Bishop, Skald – and Music, The Orkney Earldom of the Twelfth Century. A Musicological Study., Ph.D. Thesis, Uppsala: Uppsala Universitet, 1985.

After the title we get the unusual double punctuation "**.,**", this is due to the `\adddot` in

https://github.com/josephwright/biblatex-chem/blob/40e438da597922932050491c7e36232b8646d7a6/chem-acs.bbx#L110

and

https://github.com/josephwright/biblatex-chem/blob/40e438da597922932050491c7e36232b8646d7a6/chem-biochem.bbx#L92

should that have been `\isdot`?

**Comment by josephwright** [comment]
No, I think more that it shouldn't be there and the unit added should force a dot. Or course, I can't quite get it right ... adding `\setunit*{\adddot\space}` isn't quite right ....

**Comment by moewew** [comment]
I definitely do *not* approve of it, but
```latex
\DeclareFieldFormat*{title}{#1\addperiod} 
```
might do what you want. `\addot` doesn't work because "abbreviation-dot+comma" is a valid punctuation combination, but "period+comma" isn't and gets normalised to "period" only.

`\setunit` and `\setunit*` will be overridden by a following `\newunit`/`\setunit`, so it can't be used. The obvious candidate would be the persistent `\printunit*`, but I've learnt to be careful with `\printunit` because it can't be overruled - still I fell `\printunit` would be nicer than adding punctuation to field formats, which I consider a no-go.

**Comment by josephwright** [comment]
I think `\printunit` is right here: will adjust.
